### ISSUE TITLE
Index out of range error in buffer.js caused by A* callback

### ISSUE THREAD

**Issue by Darker** [andrewrk/mineflayer-navigate#25]
This is an error that randomly occured while my bot was walking around the world (in Nether):

      buffer.js:506
          throw new RangeError('index out of range');
          ^
      RangeError: index out of range
          at checkOffset (buffer.js:506:11)
          at Buffer.readUInt8 (buffer.js:544:5)
          at nib (C:\Users\Jakub\node_modules\mineflayer\lib\plugins\blocks.js:116:31)
          at Bot.blockAt (C:\Users\Jakub\node_modules\mineflayer\lib\plugins\blocks.js:102:22)
          at properties (C:\Users\Jakub\node_modules\mineflayer-navigate\index.js:326:25)
          at C:\Users\Jakub\node_modules\mineflayer-navigate\index.js:309:20
          at Array.forEach (native)
          at Object.getNeighbors [as neighbor] (C:\Users\Jakub\node_modules\mineflayer-navigate\index.js:187:30)
          at aStar (C:\Users\Jakub\node_modules\a-star\index.js:52:28)
          at findPathSync (C:\Users\Jakub\node_modules\mineflayer-navigate\index.js:72:19)

Probably it's checking non-existent blocks or something like that. I don't know how to fix it :(

**Comment by pr3mar** [comment]
I got the same problem while parsing a binary file with ~12Mx28B records . Any help?

**Comment by Darker** [comment]
I don't think these errors are necessarily connected. Index out of range can mean anything.
